name: Unpack Final Zip

on:
  workflow_dispatch:   # <-- this line enables the Run button
  push:
    branches: [ main ]

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip site
        run: |
          unzip -o krenari_eagle_final.zip -d .
